# Generated by Django 5.2.14 on 2026-05-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ens_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=42)),
                ('reverse_verified', models.BooleanField(default=False)),
                ('records', models.JSONField(blank=True, default=dict)),
                ('contenthash', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
