# Generated by Django 5.2.14 on 2026-05-21 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=42),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['resolved_at'], name='ens_profile_resolve_2b4799_idx'),
        ),
    ]
