# Generated by Django 5.2.14 on 2026-05-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ens_profiles', '0002_profile_created_at_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_a', models.CharField(max_length=255)),
                ('name_b', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name_a'], name='ens_profile_name_a_04f9c7_idx'), models.Index(fields=['name_b'], name='ens_profile_name_b_af6e81_idx')],
                'constraints': [models.UniqueConstraint(fields=('name_a', 'name_b'), name='unique_friendship_pair'), models.CheckConstraint(condition=models.Q(('name_a__lt', models.F('name_b'))), name='canonical_order')],
            },
        ),
    ]
